version: '3.7'

services:
  fastapi:
    build: .
    container_name: ark-invest-api
    restart: always
    ports:
      - "80:80"
    environment:
      - WORKERS_PER_CORE=3
      - MAX_WORKERS=6
    env_file:
      - fastapi.env
