version: '3.7'

services:
  fastapi:
    build: .
    container_name: ark-invest-api
    restart: always
    ports:
      - "80:80"
    environment:
      - WEB_CONCURRENCY=2
    env_file:
      - fastapi.env
