[tool.poetry]
name = "ark-invest-api"
version = "2.4.2"
description = "API for tracking holdings and trades of ARK Invest funds."
authors = ["Fredrik Haarstad <codemonkey@zomg.no>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.104.0"
requests = "^2.31.0"
psycopg2-binary = "^2.9.9"
python-dateutil = "^2.8.2"
SQLAlchemy = "^2.0.22"
uvicorn = "^0.23.2"

[tool.poetry.dev-dependencies]
black = "^23.10.0"
isort = "^5.12.0"
pytest = "^7.4.2"

[tool.poetry.group.dev.dependencies]
httpx = "^0.25.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
