[tool.poetry]
name = "ark-invest-api"
version = "2.4.1"
description = "API for tracking holdings and trades of ARK Invest funds."
authors = ["Fredrik Haarstad <codemonkey@zomg.no>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.100.0"
requests = "^2.31.0"
psycopg2-binary = "^2.9.6"
python-dateutil = "^2.8.2"
SQLAlchemy = "^2.0.16"
uvicorn = "^0.22.0"

[tool.poetry.dev-dependencies]
black = "^23.3.0"
isort = "^5.12.0"
pytest = "^7.3.2"

[tool.poetry.group.dev.dependencies]
httpx = "^0.24.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
