[tool.poetry]
name = "ark-invest-api"
version = "2.4.0"
description = "API for tracking holdings and trades of ARK Invest funds."
authors = ["Fredrik Haarstad <codemonkey@zomg.no>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.79.0"
requests = "^2.28.0"
psycopg2-binary = "^2.9.3"
python-dateutil = "^2.8.2"
SQLAlchemy = "^1.4.39"
uvicorn = "^0.18.1"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
isort = "^5.10.1"
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
