[tool.poetry]
name = "ark-invest-api"
version = "2.4.1"
description = "API for tracking holdings and trades of ARK Invest funds."
authors = ["Fredrik Haarstad <codemonkey@zomg.no>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.92.0"
requests = "^2.28.2"
psycopg2-binary = "^2.9.5"
python-dateutil = "^2.8.2"
SQLAlchemy = "^2.0.4"
uvicorn = "^0.20.0"

[tool.poetry.dev-dependencies]
black = "^23.1.0"
isort = "^5.12.0"
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
