# Data update interval
UPDATE_INTERVAL_HOLDINGS = 300
UPDATE_INTERVAL_TRADES = 300

# Custom OpenAPI
OPENAPI_TITLE = ""
OPENAPI_API_VERSION = ""
OPENAPI_DESCRIPTION = ""
OPENAPI_CONTACT = ""
OPENAPI_HOST = ""
OPENAPI_SERVER_URL = ""
OPENAPI_SERVER_BASEPATH = ""
OPENAPI_EXTERNALDOCS_DESC = ""
OPENAPI_EXTERNALDOCS_URL = ""

# ARK settings
FUNDS = []

BASE_URL_HOLDINGS = ""
BASE_URL_TRADES = ""
TRADE_STATUS_URL = ""

FUND_HOLDINGS_FILES = {}

# Example json output
HOLDINGS_FUND_EXAMPLE = {}

TRADES_FUND_EXAMPLE = {}
